baseURL = "https://awesome.pranshugaba.com/"
languageCode = "en-in"
title = "Pranshu Gaba"
theme = "awesome"

enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
footnoteReturnLinkContents = "↩"
paginate = 10 # Default number of elements per page in pagination.
summaryLength = 50 # Length of text in words to show in a .Summary
titleCaseStyle = "Chicago"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[markup]
    [markup.highlight]
        style = "dracula"

[minify]
minifyOutput = true

[taxonomies]
    tag = "tags"

[params]
mainSections = ["articles", "poems", "posts", "puzzles", "stories"]
AuthorName = "Pranshu Gaba"
GitHubUser = "pranshugaba"