baseURL = "https://pranshugaba.com/"
languageCode = "en"
title = "Pranshu Gaba"
theme = "awesome"


copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
footnoteReturnLinkContents = "↩"
paginate = 10                                                                                                  # Default number of elements per page in pagination.
summaryLength = 50                                                                                             # Length of text in words to show in a .Summary
titleCaseStyle = "Chicago"

disablePathToLower = true

timeout = 300000

[frontmatter]
lastmod = ["lastmod", ":git", ":default"]

[markup]
[markup.highlight]
style = "perldoc"
noClasses = false
[markup.goldmark]
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true

[minify]
minifyOutput = true

[taxonomies]
tag = "tags"


[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10


[params]
mainSections = [
    "posts",
    "a-propos-de-moi",
    "thoughts",
    "dev",
    "maths",
    "trips",
    "thoughts",
    "recipes",
    "poems",
    "puzzles",
    "stories",
    "comics",
    "minis",
    "newsletter",
]
AuthorName = "Pranshu Gaba"
GitHubUser = "pranshugaba"

[author]
name = "Pranshu Gaba"
email = "pranshu@pranshugaba.com"
