baseURL = "https://pranshugaba.com/"
languageCode = "en"
title = "Pranshu Gaba"
theme = "awesome"


copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
footnoteReturnLinkContents = "↩"
summaryLength = 50   # Length of text in words to show in a .Summary
titleCaseStyle = "Chicago"

disablePathToLower = true

timeout = 300000



[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'

[frontmatter]
lastmod = ["lastmod", ":git", ":default"]

[markup]
  [markup.highlight]
    style = "perldoc"
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


[minify]
  minifyOutput = true

[taxonomies]
  tag = "tags"


[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10


[params]
  mainSections = [
      "articles",
      "dev",
      "trips",
      "recipes",
      "poems",
      "puzzles",
      "stories",
      "comics",
      "minis",
      "newsletter",
  ]
  AuthorName = "Pranshu Gaba"
  GitHubUser = "pranshugaba"

[author]
  name = "Pranshu Gaba"
  email = "pranshu@pranshugaba.com"
