baseURL = "https://pranshugaba.com/"
languageCode = "en"
title = "Pranshu Gaba"
theme = "awesome"


copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
footnoteReturnLinkContents = "↩"
paginate = 10 # Default number of elements per page in pagination.
summaryLength = 50 # Length of text in words to show in a .Summary
titleCaseStyle = "Chicago"


[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[markup]
[markup.highlight]
pygmentsUseClasses = true
[markup.goldmark.renderer]
unsafe = true

[minify]
minifyOutput = true

[taxonomies]
tag = "tags"

[params]
mainSections = ["poems", "posts", "puzzles", "stories"]
AuthorName = "Pranshu Gaba"
GitHubUser = "pranshugaba"


[author]
name = "Pranshu Gaba"
email = "pranshu@pranshugaba.com"
