baseURL = "https://awesome.pranshugaba.com/"
languageCode = "en-in"
title = "Pranshu Gaba"
theme = "awesome"

enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
footnoteReturnLinkContents = "↩"
paginate = 10 # Default number of elements per page in pagination.
summaryLength = 50 # Length of text in words to show in a .Summary
titleCaseStyle = "Chicago"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[minify]
minifyOutput = true

[params]
mainSections = ["articles", "poems"]
AuthorName = "Pranshu Gaba"
GitHubUser = "pranshugaba"

[taxonomies]
tag = "tags"
