[[photos]]
filename = "img/IMG_20250316_061419068_HDR.jpg"
alt = """
A gym with a human-sized figure of the Incredible Hulk on the signboard.
"""
caption = """
The Incredible Hulk works out at this gym. 
"""
 
[[photos]]
filename = "img/IMG_20250316_062049472.jpg"
alt = """
Buses ply along at Godrej chowk.
"""
caption = """
A view from atop the Kemps Corner flyover.
Buses ply along at Godrej chowk.
"""
 
[[photos]]
filename = "img/IMG_20250316_062625536_HDR.jpg"
alt = """
People jog on the road, with clouds in the backdrop.
"""
caption = """
Joggers are out for an early-morning jog, with beautiful broken clouds in the backdrop.
"""
 
[[photos]]
filename = "img/IMG_20250316_062715339.jpg"
alt = """
Coastal road in Worli.
"""
caption = """
The Worli seaface is ruined, thanks to the coastal road.
"""
 
[[photos]]
filename = "img/IMG_20250316_063904569_HDR.jpg"
alt = """
Two bunnies ride a tandem cycle on the divider. They cast a shadow on the road. 
"""
caption = """
Two bunnies ride a tandem cycle on the divider. They cast a shadow on the road. 
"""
 
[[photos]]
filename = "img/IMG_20250316_063931226_HDR.jpg"
alt = """
Front view of the two bunnies on the tandem cycle.
"""
caption = """
Front view of the two bunnies. 
The car is going to overtake them.
"""
 
[[photos]]
filename = "img/IMG_20250316_064038185_HDR.jpg"
alt = """
Side view of the two bunnies on the tandem cycle. 
"""
caption = """
They look so cute.
"""
 
[[photos]]
filename = "img/IMG_20250316_064153963.jpg"
alt = """
The bunnies surrounded by traffic. 
"""
caption = """
The bunnies bravely weave through the traffic.
"""
 
[[photos]]
filename = "img/IMG_20250316_064312027_HDR.jpg"
alt = """
A photo of Pranshu Gaba, wearing a helmet and a Napoli jersey.
"""
caption = """
I am one with the bunnies. 
"""
 
[[photos]]
filename = "img/IMG_20250316_064455324_HDR.jpg"
alt = """
A tall glass skyscraper. 
"""
caption = """
A tall glass skyscraper looms over the road.
"""
 
[[photos]]
filename = "img/IMG_20250316_065329239_HDR.jpg"
alt = """
A skybridge over the road.
"""
caption = """
A skybridge connects two wings of Hinduja hospital.
"""
 
[[photos]]
filename = "img/IMG_20250316_065844512_HDR.jpg"
alt = """
Sunrays burst through the clouds. 
"""
caption = """
The sun is about to rise as sunrays burst through the clouds. 
"""
 
[[photos]]
filename = "img/IMG_20250316_065931239_HDR.jpg"
alt = """
A Bisleri truck passes by the sunburst.
"""
caption = """
A Bisleri truck passes by the sunburst.
"""
 
[[photos]]
filename = "img/IMG_20250316_070039889.jpg"
alt = """
A view of the Mithi river. 
"""
caption = """
A view of the Mithi river. 
"""
 
[[photos]]
filename = "img/IMG_20250316_070052864.jpg"
alt = """
Sunrise and sunburst. 
"""
caption = """
The sun peeks from the horizon.
"""
 
[[photos]]
filename = "img/IMG_20250316_071248993_HDR.jpg"
alt = """
A not-as-tall glass skyscraper. 
"""
caption = """
A not-as-tall glass skyscraper looms over the road.
"""
 
[[photos]]
filename = "img/IMG_20250316_072053326_HDR.jpg"
alt = """
People walk in a walkathon in Juhu.
"""
caption = """
People walk in a walkathon in Juhu.
"""
 
[[photos]]
filename = "img/IMG_20250316_072135286.jpg"
alt = """
A truck parked on the beach with a sign "7D cinmea on wheels".
"""
caption = """
For the first time in India, a truck is repurposed into a "7D cinema on wheels".
"""
 
[[photos]]
filename = "img/IMG_20250316_072137735.jpg"
alt = """
Pigeons hunt and peck in the sand at Juhu beach.
"""
caption = """
Pigeons hunt and peck in the sand.
The beach is a popular Sunday morning excursion destination.
"""
 
[[photos]]
filename = "img/IMG_20250316_072308803_HDR.jpg"
alt = """
Sunrise captured from Juhu beach.
"""
caption = """
The sun rises relentlessly.
"""
 
[[photos]]
filename = "img/IMG_20250316_072311224_HDR.jpg"
alt = """
Meditation session at the beach. 
"""
caption = """
A meditation session takes place at the beach. 
"""
 
[[photos]]
filename = "img/IMG_20250316_075101067_HDR.jpg"
alt = """
A BEST Bus plastered in watch advertisements.
"""
caption = """
This BEST bus must be very punctual.
"""
 
[[photos]]
filename = "img/IMG_20250316_080531303_HDR.jpg"
alt = """
A car juts out of a signboard.
"""
caption = """
This signboard car is perfect for the signboard Incredible Hulk.
"""
