[[photos]]
filename = "img/IMG_20210723_100339.jpg"
alt = "A person walking across a mostly deserted Juhu Beach"
caption = """
A cloudy windy day at Juhu beach. It was almost high tide too when I arrived, so the waves were huge and _so_ close to the road.

The beach was roped off, but there were a few people strolling on the beach. I could see lifeguards too in their yellow and red uniforms.
"""

[[photos]]
filename = "img/IMG_20210723_100418.jpg"
alt = "People walking on Juhu Road next to Juhu Beach"
caption = """
Grey skies and grey roads at Juhu Beach. Lovely weather.
"""

[[photos]]
filename = "img/IMG_20210723_102246.jpg"
alt = "A \"Love Earth\" sign at a road intersection"
caption = """
A fake yellow tree stands next to the "Love Earth" sign in Versova.
"""

[[photos]]
filename = "img/IMG_20210723_103511.jpg"
alt = "A deserted road with cars parked in the middle. "
caption = """
A cul-de-sac adjacent to the Central Institute of Fisheries Education, Versova.
"""

[[photos]]
filename = "img/IMG_20210723_103613.jpg"
alt = "Parked tempo covered with patches of green grass"
caption = """
Once upon a time, momos were made and served in this grass-covered tempo --- with free home delivery.
"""

[[photos]]
filename = "img/IMG_20210723_103851.jpg"
alt = "Blue shed with bowls for dog food."
caption = """
A beautiful blue shed with food for dogs.
"""

[[photos]]
filename = "img/IMG_20210723_110648.jpg"
alt = "A crow perched on a tree with a nest and no leaves."
caption = """
This tree grows on the bank of a tributary of Malad creek. A crow perches next to a nest on the tree.
"""

[[photos]]
filename = "img/IMG_20210723_111925.jpg"
alt = "A river seen from atop a bridge. A mall and a skyscraper behind it."
caption = """
A view of the Oshiwara river from atop a bridge. The river is normally full and flowing during the rainy season.
"""

[[photos]]
filename = "img/IMG_20210723_111928.jpg"
alt = "Two boys walking on the footpath. Three cyclists riding in a line. Two BEST buses pass by."
caption = """
A different view from the same spot. It's a very busy place. Two BEST buses pass by. Men in high-vis vests carry planks to build the Metro station.

A file of three cyclists (four, if you include me) ride one behind the other. 
Two friends walk on the footpath, shoulder to shoulder.
"""

[[photos]]
filename = "img/IMG_20210723_113236.jpg"
alt = "A black and white and brown dog sits on the divider in the middle of the street."
caption = """
This cute doggo sits on the divider, managing traffic in both directions.
"""

[[photos]]
filename = "img/IMG_20210723_114022.jpg"
alt = "Tall grey building in a green field."
caption = """
A grey building towers over the green foliage around it.
"""

[[photos]]
filename = "img/IMG_20210723_120648-PANO.jpg"
alt = "A water channel, with buildings in the background."
caption = """
A panorama of a different tributary of the Malad creek. The Metro line can be seen in the distance.
"""

[[photos]]
filename = "img/IMG_20210723_120956.jpg"
alt = "Three tall towers under construction."
caption = """
Towering heights in Malad.
"""
