[[photos]]
filename = "img/2021_08_19_17_00_08.jpg"
alt = "A black statue in front of a white and a blue skyscrapers."
caption = """
A tall and thin statue, just like the buildings behind it. 
The more you look at this statue, the weirder it gets.
"""

[[photos]]
filename = "img/2021_08_19_17_20_25.jpg"
alt = "A black and white cat with markings that look like a mustache."
caption = """
I spotted a cute Kitler in the wild.
"""

[[photos]]
filename = "img/2021_08_19_17_58_17.jpg"
alt = "The Taj Mahal Hotels"
caption = """
The beautiful Taj Mahal Palace and Taj Mahal Tower hotels sit facing the Gateway of India.
"""

[[photos]]
filename = "img/2021_08_19_18_01_33.jpg"
alt = "The Gateway of India"
caption = """
A group of people pose for a photo in front of the Gateway of India. 

There are loads of photographers around the Gateway. There are probably as many photographers as there are tourists here nowadays. 
They offer instant prints for just ₹30.
"""

[[photos]]
filename = "img/2021_08_19_18_06_45.jpg"
alt = "Maharashtra Police Headquarters"
caption = """
A polychromatic building with Venetian Gothic architecture that is the Maharashtra Police Headquarters.
"""

[[photos]]
filename = "img/2021_08_19_18_08_56.jpg"
alt = "An illustration on a wall of a man in BEST uniform"
caption = """
A man in BEST uniform greets passengers outside the BEST depot near the Chhatrapati Shivaji Maharaj Vastu Sangrahalaya, aka the Prince of Wales Museum of Western India, aka the Museum.
"""

[[photos]]
filename = "img/2021_08_19_18_11_21.jpg"
alt = ""
caption = """
A cat eats some evening snacks.
"""

[[photos]]
filename = "img/2021_08_19_18_11_43.jpg"
alt = ""
caption = """
The Elphinstone College, now part of the Dr. Homi Bhabha State University.
"""

[[photos]]
filename = "img/2021_08_19_18_13_49.jpg"
alt = ""
caption = """
The David Sassoon Library and Reading Room founded in 1847. Beside it is a Westside store, which opened about 10 years ago.
"""

[[photos]]
filename = "img/2021_08_19_18_14_37.jpg"
alt = ""
caption = """
Rhythm House. An iconic music store in Kala Ghoda, Fort.
"""

[[photos]]
filename = "img/2021_08_19_18_14_47.jpg"
alt = ""
caption = """
145 Kala Ghoda cafe + bar. Not to be confused with the Kala Ghoda Cafe.
"""

[[photos]]
filename = "img/2021_08_19_18_17_35.jpg"
alt = ""
caption = """
A tiny alley leads to the Bombay Stock Exchange (BSE).
"""

[[photos]]
filename = "img/2021_08_19_18_19_23.jpg"
alt = ""
caption = """
On the left, you see the Mumbai University, and in its premises, there's a clock tower.
"""

[[photos]]
filename = "img/2021_08_19_18_21_39.jpg"
alt = ""
caption = """
A closer look at the Rajabai Clock Tower, the Big Ben of Mumbai.
"""

[[photos]]
filename = "img/2021_08_19_18_22_05.jpg"
alt = ""
caption = """
A not-so-great angle of the High Court of Bombay.
"""

[[photos]]
filename = "img/2021_08_19_18_30_12.jpg"
alt = ""
caption = """
A scaffolded statue of Mahadev Govind Ranade: a scholar, a judge, and a social reformer.
"""

[[photos]]
filename = "img/2021_08_19_18_50_43.jpg"
alt = ""
caption = """
The dog that was promised. We are on a temporary metal bridge, and below us is an underground metro station under construction (not visible in picture).
"""

[[photos]]
filename = "img/2021_08_19_18_53_51.jpg"
alt = ""
caption = """
And here are the reptiles. Lizards hanging out under the strip of lights waiting for their prey.
"""

[[photos]]
filename = "img/2021_08_19_19_07_25.jpg"
alt = "A building numbered 2020."
caption = """
An auspiciously numbered building.
"""

[[photos]]
filename = "img/2021_08_19_19_08_39.jpg"
alt = ""
caption = """
The LIC building, lit in blue and yellow. The Canara Bank building opposite Town Hall in Bangalore is similarly lit. 
"""

[[photos]]
filename = "img/2021_08_19_19_31_55.jpg"
alt = ""
caption = """
A curious cat approaches the camera.
"""

[[photos]]
filename = "img/2021_08_19_19_41_32.jpg"
alt = "A pot of drinking water decorated with snow-capped mountains."
caption = """
Cool drinking water, fresh from the snowy peaks of the Himalayas.
"""

[[photos]]
filename = "img/2021_08_19_19_43_43.jpg"
alt = ""
caption = """
Some more cats.
"""

[[photos]]
filename = "img/2021_08_19_19_43_56.jpg"
alt = ""
caption = """
Even more cat. No, this is the same cat from the last picture.
"""
