[[photos]]
filename = "img/IMG_20220218_064444.jpg"
alt = """
Worli sunrise skyline
"""
caption = """
A sunrise skyline in Worli.
"""

[[photos]]
filename = "img/IMG_20220218_070049.jpg"
alt = """
Moonset over the Mithi river
"""
caption = """
The moon sets in the western sky as the Mithi river flows into Mahim bay.
"""

[[photos]]
filename = "img/IMG_20220218_070111.jpg"
alt = """
Swirling waves
"""
caption = """
Swirling waves seen in Mithi river.
"""

[[photos]]
filename = "img/IMG_20220218_070801.jpg"
alt = """
Cat looking at camera
"""
caption = """
I met a chonky cat in Bandra. 
"""

[[photos]]
filename = "img/IMG_20220218_070804.jpg"
alt = """
Cat begins to approach the camera
"""
caption = """
It began walking towards me...
"""

[[photos]]
filename = "img/IMG_20220218_070806.jpg"
alt = """
Cat licking the camera
"""
caption = """
... and it sniffed and licked my phone.
"""

[[photos]]
filename = "img/IMG_20220218_071051.jpg"
alt = """
The cat looks in the distance
"""
caption = """
It stood brooding the distance. 
"""

[[photos]]
filename = "img/IMG_20220218_071115.jpg"
alt = """
Cat looks at the camera
"""
caption = """
It posed for a shot.
"""

[[photos]]
filename = "img/IMG_20220218_071724.jpg"
alt = """
Selfie of Pranshu with cat
"""
caption = """
It sat on my lap. 
"""

[[photos]]
filename = "img/IMG_20220218_073114.jpg"
alt = """
Sunrising behind a highrise
"""
caption = """
The sun rose from behind the building. 
"""

[[photos]]
filename = "img/IMG_20220218_073254.jpg"
alt = """
Exterior view of Carter Road Social
"""
caption = """
Padma Bhushan Pran Chowk.
"""

[[photos]]
filename = "img/IMG_20220218_073310.jpg"
alt = """
Fluffy white cat
"""
caption = """
A fluffy white cat. 
"""

[[photos]]
filename = "img/IMG_20220218_073353.jpg"
alt = """
Exterior view of Carter Road Social
"""
caption = """
Starbucks and Carter Road Social.
"""

[[photos]]
filename = "img/IMG_20220218_075709.jpg"
alt = """
People walking on Juhu beach
"""
caption = """
People out for morning walks and jogs and frisbee. Many with pets.
"""

[[photos]]
filename = "img/IMG_20220218_075727.jpg"
alt = """
Dogs at Juhu beach
"""
caption = """
Batmobile.
"""

[[photos]]
filename = "img/IMG_20220218_075830.jpg"
alt = """
Odometer on cycle handlebar
"""
caption = """
My odometer read 36.36 km.
"""

[[photos]]
filename = "img/IMG_20220218_083545.jpg"
alt = """
Brown puppies licking something off the ground
"""
caption = """
I met a litter of puppies in Bangur nagar. The rightmost one is named _Rainbow_.
"""

[[photos]]
filename = "img/IMG_20220218_083547.jpg"
alt = """
White and cream puppy sniffing the ground
"""
caption = """
Another puppy of the same litter. 
"""

