[[photos]]
filename = "img/IMG_20250906_061537725.webp"
alt = """
A faint silhouette of an electricity pylon and overhead powerlines against a backdrop of a dark blue sky.
"""
caption = """
The faintest glimpse of sunlight in the sky.
"""

[[photos]]
filename = "img/IMG_20250906_063200633.webp"
alt = """
Two benches in a forest.
"""
caption = """
Two benches in the middle of the woods.
"""


[[photos]]
filename = "img/IMG_20250906_064126058_HDR.webp"
alt = """
A mountain covered in trees.
"""
caption = """
The trees at the top of the mountain begin to see the sunlight. It is still dark below.
"""

[[photos]]
filename = "img/IMG_20250906_064215977.webp"
alt = """
A trail towered over by trees on both sides.
"""
caption = """
Tall trees tower the trail.
"""

[[photos]]
filename = "img/IMG_20250906_064620874_HDR.webp"
alt = """
A view of houses and trees in the valley with golden clouds in the blue sky.
"""
caption = """
Houses and trees in the valley come to light as the sun begins to rise.
"""

[[photos]]
filename = "img/IMG_20250906_065356695_HDR.webp"
alt = """
A bench alongside overlooks a fence.
"""
caption = """
If you sit on the bench, you see the fence...
"""

[[photos]]
filename = "img/IMG_20250906_065407298_HDR.webp"
alt = """
Brown sheep grazing in a fenced pasture.
"""
caption = """
... and the sheep behind the fence see you.
"""

[[photos]]
filename = "img/IMG_20250906_065441731_HDR.webp"
alt = """
A road sign with printed text "Forstwirt - schaftlicher Verkehr frei" and handwritten text "Help me".
"""
caption = """
The road is traffic-free. The sign says "Help me".
"""

[[photos]]
filename = "img/IMG_20250906_065446477_HDR.webp"
alt = """
A trail cutting through the trees.
"""
caption = """
It is still dark in the woods.
"""

[[photos]]
filename = "img/IMG_20250906_065840131_HDR.webp"
alt = """
A trail marker in the woods.
"""
caption = """
Continue left to stay on trail #2.
"""

[[photos]]
filename = "img/IMG_20250906_070555697.webp"
alt = """
A giant metallic structure that is a parking lot.
"""
caption = """
A parking lot from afar.
"""

[[photos]]
filename = "img/IMG_20250906_070703447_HDR.webp"
alt = """
Four floors of parking lot in the background, grass in the foreground.
"""
caption = """
The (empty) parking lot from up close.
"""

[[photos]]
filename = "img/IMG_20250906_071952052_HDR.webp"
alt = """
Two bicycles: one on the ground and one up above.
"""
caption = """
A cycle on the ground, a cycle up above.
"""

[[photos]]
filename = "img/IMG_20250906_072447557.webp"
alt = """
A side view of a metal structure for parking cycles.
"""
caption = """
Concentric circles for parking cycles.
"""

[[photos]]
filename = "img/IMG_20250906_072810823_HDR.webp"
alt = """
The Sportcampus building with bright blue skies.
"""
caption = """
The end of the trail. It is now fully bright outside. We have returned back to the starting point.
"""
